# More syntax details at: https://docs.travis-ci.com/user/customizing-the-build
# Workaround present for https://github.com/sunqm/pyscf/issues/71

sudo: false
language: python
group: deprecated-2017Q4
os: linux

git:
  depth: 3

matrix:
  include:
    - dist: trusty

virtualenv:
    system_site_packages: true
    
before_install:
    - >
      sudo apt-get -qq install 
      gcc 
      libblas-dev
      cmake
      python-pip
    - pip install numpy scipy h5py nose nose-exclude
    
install:
    - mkdir build && cd build && cmake .. && make && cd ..

script:
  - python perf.py
