# More syntax details at: https://docs.travis-ci.com/user/customizing-the-build
# Workaround present for https://github.com/sunqm/pyscf/issues/71

sudo: false
dist: trusty
language: python
group: deprecated-2017Q4

git:
  depth: 3

addons:
  apt:
    packages:
    - gcc
    - libopenblas-dev
    - cmake

python:
  - 2.7

#virtualenv:  affect python 3.5 3.6?
#    system_site_packages: true
    
before_install:
  - pip install numpy
    
install:
  - mkdir build && cd build && cmake .. && make && cd ..

script:
  - python perf.py
