# More syntax details at: https://docs.travis-ci.com/user/customizing-the-build
# Workaround present for https://github.com/sunqm/pyscf/issues/71

sudo: false
language: python
group: deprecated-2017Q4
dist: trusty

git:
  depth: 3

addons:
  apt:
    packages:
    - gcc
    - libblas-dev
    - cmake

before_install:
  - pip install numpy
    
install:
  - >
    blas_dir=`python -c "import os, numpy; print(os.path.dirname(numpy.__file__))"`/.libs
    ln -s ${blas_dir}/lib* ./
    echo 'set(BLAS_LIBRARIES "-L${PROJECT_SOURCE_DIR} '`ls ${blas_dir}/libopenblas*`'")' > cmake.arch.inc
  - ls -l && cat cmake.arch.inc
  - mkdir build && cd build && cmake .. && make && cd ..

script:
  - python perf.py
