# More syntax details at: https://docs.travis-ci.com/user/customizing-the-build
# Workaround present for https://github.com/sunqm/pyscf/issues/71

sudo: false
language: python
group: deprecated-2017Q4
dist: trusty

git:
  depth: 3

before_install:
    - >
      sudo apt-get -qq install 
      gcc 
      libopenblas-dev
      cmake
      python-pip
    - pip install numpy
    
install:
    - mkdir build && cd build && cmake .. && make && cd ..

script:
  - python perf.py
