# More syntax details at: https://docs.travis-ci.com/user/customizing-the-build
# Workaround present for https://github.com/sunqm/pyscf/issues/71

sudo: false
language: python
group: deprecated-2017Q4
dist: trusty

git:
  depth: 3

addons:
  apt:
    packages:
    - gcc
    - libblas-dev
    - cmake

before_install:
  - pip install numpy
    
install:
  - ln -s `python -c "import os, numpy; print(os.path.dirname(numpy.__file__))"`/.libs/lib* ./ &&
    blaslib=`basename libopenblas* .so | cut -c 4-` &&
    echo 'set(BLAS_LIBRARIES "-L${PROJECT_SOURCE_DIR} -l'${blaslib}'")' > cmake.arch.inc
  - mkdir build && cd build && cmake .. && make && cd ..

script:
  - echo $TRAVIS_BUILD_DIR
  - pwd && python perf.py
